%% NOTE TEORICHE - VERIFICA NOMINALE E ROBUSTA DEI CONTROLLORI
% Valuta per ciascun controllore stabilita' nominale (NS), prestazione
% nominale (NP), stabilita' robusta (RS) e prestazione robusta (RP), oltre
% alle funzioni S, KS e T e alle metriche temporali. Le analisi mu/worst
% case quantificano il comportamento rispetto alla struttura di incertezza
% invece di limitarsi al solo modello nominale.
%

%% HINF_ANALYSIS
%
% Analisi comparativa completa (H-infinity, PID strutturato e H2):
%
% NS - Nominal Stability
% NP - Nominal Performance
% RS - Robust Stability
% RP - Robust Performance
%
% + time-domain metrics:
%
% Rise Time
% Settling Time
% Overshoot
close all;
clc;
load('HINF_setup.mat');
load('HINF_controllers.mat');
load('H2_controller.mat');
I2 = eye(2);

%% ========================================================================
% OPZIONI WCGAIN
%
% Strategia:
%
% 1) si prova prima il metodo standard;
%
% 2) SOLO se compare l'errore
%
%       "Invalid MU upper bound"
%
%    si ripete il calcolo utilizzando
%
%       MussvOptions = 'a'
%
% in modo analogo a MU_analysis_comparison.m.
% ========================================================================
wcOptsFast = wcOptions;
wcOptsAccurate = ...
    wcOptions( ...
    'MussvOptions','a');
%% ========================================================================
% 1. CONTROLLORI
% ========================================================================
controllersScaled = {
    K_mix_scaled
    K_hinfsyn_scaled
    K_pidcomp_scaled
    K_h2_scaled
};
controllersPhysical = {
    K_mix
    K_hinfsyn
    K_pidcomp
    K_h2
};
controllerNames = {
    'mixsyn'
    'hinfsyn'
    'PID + compensator'
    'H2'
};
nControllers = ...
    numel(controllersScaled);
% Ridimensiona le celle dipendenti dal numero di controllori dopo
% l'aggiunta del controllore H2.
wcuRS_all = cell(nControllers,1);
wcuRP_all = cell(nControllers,1);
robSensitivity_all = cell(nControllers,1);

%% ========================================================================
% 2. PREALLOCAZIONE
% ========================================================================
controllerOrder = ...
    zeros(nControllers,1);
maxRealPoleNominal = ...
    zeros(nControllers,1);
gammaNominal = ...
    zeros(nControllers,1);
performance_WS = ...
    zeros(nControllers,1);
performance_WU = ...
    zeros(nControllers,1);
performance_WT = ...
    zeros(nControllers,1);
robustStabilityLower = ...
    zeros(nControllers,1);
robustStabilityUpper = ...
    zeros(nControllers,1);
worstCaseGainLower = ...
    zeros(nControllers,1);
worstCaseGainUpper = ...
    zeros(nControllers,1);
muRSpeakLower = ...
    zeros(nControllers,1);
muRSpeakUpper = ...
    zeros(nControllers,1);
muRPpeakLower = ...
    zeros(nControllers,1);
muRPpeakUpper = ...
    zeros(nControllers,1);
NS_pass = false(nControllers,1);
NP_pass = false(nControllers,1);
RS_pass = false(nControllers,1);
RP_pass = false(nControllers,1);
freq_WS    = zeros(nControllers,1);
freq_WU    = zeros(nControllers,1);
freq_WT    = zeros(nControllers,1);
freqGamma  = zeros(nControllers,1);

%% Time metrics
pitchRiseTime = ...
    zeros(nControllers,1);
pitchSettlingTime = ...
    zeros(nControllers,1);
pitchOvershoot = ...
    zeros(nControllers,1);
yawRiseTime = ...
    zeros(nControllers,1);
yawSettlingTime = ...
    zeros(nControllers,1);
yawOvershoot = ...
    zeros(nControllers,1);
PitchTimePass = ...
    false(nControllers,1);
PitchOvershootPass = ...
    false(nControllers,1);
YawTimePass = ...
    false(nControllers,1);
YawOvershootPass = ...
    false(nControllers,1);

%% Celle
S_scaled_all = ...
    cell(nControllers,1);
T_scaled_all = ...
    cell(nControllers,1);
KS_scaled_all = ...
    cell(nControllers,1);
S_phys_all = ...
    cell(nControllers,1);
T_phys_all = ...
    cell(nControllers,1);
KS_phys_all = ...
    cell(nControllers,1);
GS_phys_all = ...
    cell(nControllers,1);
muNP_all = ...
    cell(nControllers,1);
muRSupper_all = ...
    cell(nControllers,1);
muRSlower_all = ...
    cell(nControllers,1);
muRPupper_all = ...
    cell(nControllers,1);
muRPlower_all = ...
    cell(nControllers,1);

%% ========================================================================
% 3. ANALISI
% ========================================================================
for k = 1:nControllers
    Ks = controllersScaled{k};
    Kp = controllersPhysical{k};
    fprintf('\n\n');
    fprintf('############################################################\n');
    fprintf('%s\n',upper(controllerNames{k}));
    fprintf('############################################################\n');
    controllerOrder(k) = ...
        order(Ks);

    %% ====================================================================
    % 3.1 LOOP NOMINALE NORMALIZZATO
    % =====================================================================
    Ls = G_scaled*Ks;
    Ss = feedback(I2,Ls);
    Ts = feedback(Ls,I2);
    KSs = Ks*Ss;
    S_scaled_all{k} = ...
        minreal(Ss,1e-7);
    T_scaled_all{k} = ...
        minreal(Ts,1e-7);
    KS_scaled_all{k} = ...
        minreal(KSs,1e-7);

    %% ====================================================================
    % 3.2 NS
    % =====================================================================
    polesNom = ...
        pole(Ts);
    maxRealPoleNominal(k) = ...
        max(real(polesNom));
    NS_pass(k) = ...
        all(real(polesNom)<0);

    %% ====================================================================
    % 3.3 NP
    % =====================================================================
    WeightedNominalCL = [
        WS*Ss
        WU*KSs
        WT*Ts
    ];
    gammaNominal(k) = ...
        hinfnorm( ...
            minreal( ...
                WeightedNominalCL, ...
                1e-7));
    NP_pass(k) = ...
        gammaNominal(k)<1;
    [performance_WS(k),freq_WS(k)] = ...
        hinfnorm( ...
        minreal( ...
        WS*Ss, ...
        1e-7));
    [performance_WU(k),freq_WU(k)] = ...
        hinfnorm( ...
        minreal( ...
        WU*KSs, ...
        1e-7));
    [performance_WT(k),freq_WT(k)] = ...
        hinfnorm( ...
        minreal( ...
        WT*Ts, ...
        1e-7));
    [gammaNominal(k),freqGamma(k)] = ...
        hinfnorm( ...
        minreal( ...
        WeightedNominalCL, ...
        1e-7));
    fprintf('\nPicchi nominali in frequenza:\n');
    fprintf('WS*S  : %.6f a %.6f rad/s\n', ...
        performance_WS(k), ...
        freq_WS(k));
    fprintf('WU*KS : %.6f a %.6f rad/s\n', ...
        performance_WU(k), ...
        freq_WU(k));
    fprintf('WT*T  : %.6f a %.6f rad/s\n', ...
        performance_WT(k), ...
        freq_WT(k));
    fprintf('Gamma : %.6f a %.6f rad/s\n', ...
        gammaNominal(k), ...
        freqGamma(k));

    %% Profilo NP
    CLfrd = ...
        frd( ...
            WeightedNominalCL, ...
            omegaHinf);
    svNom = ...
        sigma( ...
            CLfrd, ...
            omegaHinf);
    muNP_all{k} = ...
        squeeze( ...
            max(svNom,[],1));

    %% ====================================================================
    % 3.4 MODELLO INCERTO
    % =====================================================================
    Lunc = ...
        G_uncertain_scaled * ...
        Ks;
    Sunc = ...
        feedback( ...
            I2, ...
            Lunc);
    Tunc = ...
        feedback( ...
            Lunc, ...
            I2);
    KSunc = ...
        Ks*Sunc;
    WeightedUncertainCL = [
        WS*Sunc
        WU*KSunc
        WT*Tunc
    ];

    %% ====================================================================
    % 3.5 RS
    % =====================================================================
    robOpts = ...
        robOptions( ...
        'Sensitivity','on');
    [stabMargin,wcuRS,infoRS] = ...
        robstab( ...
        Tunc, ...
        robOpts);
    robustStabilityLower(k) = ...
        stabMargin.LowerBound;
    robustStabilityUpper(k) = ...
        stabMargin.UpperBound;
    RS_pass(k) = ...
        stabMargin.LowerBound > 1;
    wcuRS_all{k} = wcuRS;
    robSensitivity_all{k} = ...
        infoRS.Sensitivity;

    %% ====================================================================
    % 3.6 RP - ROBUST PERFORMANCE VIA WCGAIN
    %
    % Strategia:
    %
    % 1) tentativo standard, piu' veloce;
    %
    % 2) se MATLAB restituisce l'errore
    %
    %       "Invalid MU upper bound"
    %
    %    viene ripetuto automaticamente wcgain con
    %
    %       MussvOptions = 'a'
    %
    % 3) robgain viene utilizzato come verifica indipendente
    %    del requisito ||Tzw||_inf < 1 per ogni incertezza.
    % =====================================================================
    fprintf('\nRunning wcgain - %s...\n', ...
        controllerNames{k});
    tic;
    try

        %% ----------------------------------------------------------------
        % TENTATIVO STANDARD
        % -----------------------------------------------------------------
        [wcGain,wcuRP,infoWCGain] = ...
            wcgain( ...
                WeightedUncertainCL, ...
                wcOptsFast);
        if ~isfinite(wcGain.UpperBound)
            fprintf('\n');
            fprintf(['Standard wcgain returned a non-finite upper bound.\n']);
            fprintf(['Retrying wcgain with ' ...
                'MussvOptions = ''a''...\n']);
            [wcGain,wcuRP,infoWCGain] = ...
                wcgain( ...
                WeightedUncertainCL, ...
                wcOptsAccurate);
            fprintf('wcgain fallback method successful.\n');
        else
            fprintf('wcgain standard method successful.\n');
        end
    catch ME

        %% ----------------------------------------------------------------
        % FALLBACK
        % -----------------------------------------------------------------
        if contains( ...
                ME.message, ...
                'Invalid MU upper bound', ...
                'IgnoreCase',true)
            fprintf('\n');
            fprintf(['Standard wcgain failed because of an invalid ' ...
                     'MU upper bound.\n']);
            fprintf(['Retrying wcgain with ' ...
                     'MussvOptions = ''a''...\n']);
            [wcGain,wcuRP,infoWCGain] = ...
                wcgain( ...
                    WeightedUncertainCL, ...
                    wcOptsAccurate);
            fprintf('wcgain fallback method successful.\n');
        else
            % Se l'errore non e' quello associato all'upper bound di mu,
            % non viene nascosto.
            rethrow(ME);
        end
    end
    elapsedWcgain = toc;
    fprintf('wcgain completed in %.2f s.\n', ...
        elapsedWcgain);

    %% --------------------------------------------------------------------
    % MEMORIZZAZIONE WORST-CASE GAIN
    % ---------------------------------------------------------------------
    worstCaseGainLower(k) = ...
        wcGain.LowerBound;
    worstCaseGainUpper(k) = ...
        wcGain.UpperBound;
    wcuRP_all{k} = ...
        wcuRP;

    %% --------------------------------------------------------------------
    % TEST ROBUST PERFORMANCE
    %
    % RP garantita se il WORST-CASE gain e' < 1.
    % Per sicurezza utilizziamo l'upper bound.
    % ---------------------------------------------------------------------
    RP_pass(k) = ...
        worstCaseGainUpper(k) < 1;
    fprintf( ...
        'Worst-case gain = [%.6f, %.6f]\n', ...
        worstCaseGainLower(k), ...
        worstCaseGainUpper(k));

    %% --------------------------------------------------------------------
    % VERIFICA INDIPENDENTE CON ROBGAIN
    %
    % robgain(...,1) verifica la prestazione:
    %
    %       ||WeightedUncertainCL||_inf < 1
    %
    % per tutta la famiglia incerta.
    % ---------------------------------------------------------------------
    [performanceMargin,wcuRobGain,infoRobGain] = ...
        robgain( ...
            WeightedUncertainCL, ...
            1);
    fprintf( ...
        'Robust performance margin = [%.6f, %.6f]\n', ...
        performanceMargin.LowerBound, ...
        performanceMargin.UpperBound);
    fprintf('\nRobust performance margin = [%.6f %.6f]\n', ...
        performanceMargin.LowerBound, ...
        performanceMargin.UpperBound);

    %% ====================================================================
    % 3.7 MU ANALYSIS
    % =====================================================================
    [Mdelta,Delta,BlockStructure] = ...
        lftdata( ...
            WeightedUncertainCL);
    nDelta = ...
        size(Delta,1);

    %% RS
    M11 = ...
        Mdelta( ...
            1:nDelta, ...
            1:nDelta);
    muRSbounds = ...
        mussv( ...
            frd( ...
                M11, ...
                omegaHinf), ...
            BlockStructure);
    muRSupper = ...
        squeeze( ...
            muRSbounds.ResponseData(1,1,:));
    muRSlower = ...
        squeeze( ...
            muRSbounds.ResponseData(1,2,:));
    muRSupper_all{k} = ...
        muRSupper;
    muRSlower_all{k} = ...
        muRSlower;
    muRSpeakUpper(k) = ...
        max(muRSupper);
    muRSpeakLower(k) = ...
        max(muRSlower);

    %% RP
    nExogenous = ...
        size( ...
        WeightedUncertainCL, ...
        2);
    nPerformance = ...
        size( ...
        WeightedUncertainCL, ...
        1);
    % --- FIX PER L'ERRORE VERTCAT CON LA STRUCT ---
    BlockStructureRP = BlockStructure;
    % Clona il primo blocco per mantenere i campi interni di MATLAB allineati
    perfBlock = BlockStructureRP(1);
    perfBlock.Name = 'Performance';
    perfBlock.Type = 'ucomplexm';
    perfBlock.Size = [nExogenous, nPerformance];
    perfBlock.Occurrences = 1;
    % Aggiunge il blocco prestazionale in coda alla struttura
    BlockStructureRP(end+1) = perfBlock;
    % ----------------------------------------------
    muRPbounds = ...
        mussv( ...
        frd( ...
        Mdelta, ...
        omegaHinf), ...
        BlockStructureRP);
    % --- QUESTA PARTE SOTTO RIMANE IDENTICA ALL'ORIGINALE ---
    muRPupper = ...
        squeeze( ...
        muRPbounds.ResponseData(1,1,:));
    muRPlower = ...
        squeeze( ...
        muRPbounds.ResponseData(1,2,:));
    muRPupper_all{k} = ...
        muRPupper;
    muRPlower_all{k} = ...
        muRPlower;
    muRPpeakUpper(k) = ...
        max(muRPupper);
    muRPpeakLower(k) = ...
        max(muRPlower);
    RP_pass(k) = muRPpeakUpper(k) < 1;

    %% ====================================================================
    % 3.8 LOOP FISICO
    % =====================================================================
    Lp = ...
        G_nominal*Kp;
    Sp = ...
        feedback(I2,Lp);
    Tp = ...
        feedback(Lp,I2);
    KSp = ...
        Kp*Sp;
    GSp = ...
        Sp*G_nominal;
    S_phys_all{k} = ...
        minreal(Sp,1e-7);
    T_phys_all{k} = ...
        minreal(Tp,1e-7);
    KS_phys_all{k} = ...
        minreal(KSp,1e-7);
    GS_phys_all{k} = ...
        minreal(GSp,1e-7);
end

%% ========================================================================
% 4. METRICHE TEMPORALI
% ========================================================================
tStep = ...
    0:0.005:12;
for k = 1:nControllers

    %% --------------------------------------------------------------------
    % PITCH
    % ---------------------------------------------------------------------
    pitchSystem = ...
        T_phys_all{k}(1,1);
    [yPitch,tPitch] = ...
        step( ...
            pitchSystem * ...
            reference.alphaStep, ...
            tStep);
    yPitch = ...
        squeeze(yPitch);
    pitchInfo = ...
        stepinfo( ...
            yPitch, ...
            tPitch, ...
            reference.alphaStep, ...
            'SettlingTimeThreshold',0.02);
    pitchRiseTime(k) = ...
        pitchInfo.RiseTime;
    pitchSettlingTime(k) = ...
        pitchInfo.SettlingTime;
    pitchOvershoot(k) = ...
        pitchInfo.Overshoot;
    PitchTimePass(k) = ...
        pitchSettlingTime(k) <= ...
        timeRequirements.pitchSettling;
    PitchOvershootPass(k) = ...
        pitchOvershoot(k) <= ...
        timeRequirements.pitchOvershoot;

    %% --------------------------------------------------------------------
    % YAW
    % ---------------------------------------------------------------------
    yawSystem = ...
        T_phys_all{k}(2,2);
    [yYaw,tYaw] = ...
        step( ...
            yawSystem * ...
            reference.betaStep, ...
            tStep);
    yYaw = ...
        squeeze(yYaw);
    yawInfo = ...
        stepinfo( ...
            yYaw, ...
            tYaw, ...
            reference.betaStep, ...
            'SettlingTimeThreshold',0.02);
    yawRiseTime(k) = ...
        yawInfo.RiseTime;
    yawSettlingTime(k) = ...
        yawInfo.SettlingTime;
    yawOvershoot(k) = ...
        yawInfo.Overshoot;
    YawTimePass(k) = ...
        yawSettlingTime(k) <= ...
        timeRequirements.yawSettling;
    YawOvershootPass(k) = ...
        yawOvershoot(k) <= ...
        timeRequirements.yawOvershoot;

    %% Output
    fprintf('\n============================================================\n');
    fprintf('%s - TIME RESPONSE\n',upper(controllerNames{k}));
    fprintf('============================================================\n');
    fprintf('\nPITCH\n');
    fprintf( ...
        'Rise Time     = %.4f s\n', ...
        pitchRiseTime(k));
    fprintf( ...
        'Settling Time = %.4f s\n', ...
        pitchSettlingTime(k));
    fprintf( ...
        'Overshoot     = %.2f %%\n', ...
        pitchOvershoot(k));
    fprintf('\nYAW\n');
    fprintf( ...
        'Rise Time     = %.4f s\n', ...
        yawRiseTime(k));
    fprintf( ...
        'Settling Time = %.4f s\n', ...
        yawSettlingTime(k));
    fprintf( ...
        'Overshoot     = %.2f %%\n', ...
        yawOvershoot(k));
end

%% ========================================================================
% 5. TRACKING PITCH
% ========================================================================
figure('Name','Controller comparison - Pitch reference tracking');
for k = 1:nControllers
    [y,t] = ...
        step( ...
            T_phys_all{k}(1,1) * ...
            reference.alphaStep, ...
            tStep);
    plot( ...
        t, ...
        rad2deg(squeeze(y)), ...
        'LineWidth',1.4, ...
        'Color',controller_plot_color(controllerNames{k}));
    hold on;
end
yline( ...
    rad2deg(reference.alphaStep), ...
    'k:');
grid on;
xlabel('$t\;[\mathrm{s}]$','Interpreter','latex');
ylabel('$\Delta\alpha\;[^{\circ}]$','Interpreter','latex');
title('Inseguimento del riferimento di pitch','Interpreter','latex');
legend( ...
    controllerNames{:}, ...
    'Reference', ...
    'Location','best');

%% ========================================================================
% 6. TRACKING YAW
% ========================================================================
figure('Name','Controller comparison - Yaw reference tracking');
for k = 1:nControllers
    [y,t] = ...
        step( ...
            T_phys_all{k}(2,2) * ...
            reference.betaStep, ...
            tStep);
    plot( ...
        t, ...
        rad2deg(squeeze(y)), ...
        'LineWidth',1.4, ...
        'Color',controller_plot_color(controllerNames{k}));
    hold on;
end
yline( ...
    rad2deg(reference.betaStep), ...
    'k:');
grid on;
xlabel('$t\;[\mathrm{s}]$','Interpreter','latex');
ylabel('$\Delta\beta\;[^{\circ}]$','Interpreter','latex');
title('Inseguimento del riferimento di yaw','Interpreter','latex');
legend( ...
    controllerNames{:}, ...
    'Reference', ...
    'Location','best');

%% ========================================================================
% 7. SENSITIVITY PLOTS
% =========================================================================
% Ogni controllore usa SEMPRE il proprio colore globale. Le due curve dei
% valori singolari dello stesso sistema condividono il colore e vengono
% differenziate con linea continua/tratteggiata. In questo modo il numero
% di curve non fa mai riciclare la ColorOrder di MATLAB e la legenda resta
% semanticamente corretta.

figure('Name','Controller comparison - Sensitivity function');
hold on; grid on;
for k = 1:nControllers
    plotSigmaController( ...
        S_scaled_all{k},omegaHinf,controllerNames{k});
end
plotSigmaBound(inv(WS),omegaHinf,'$W_S^{-1}$');
xlabel('$\omega\;[\mathrm{rad/s}]$','Interpreter','latex');
ylabel('Valori singolari [dB]','Interpreter','latex');
title('Funzione di sensibilita'' $S(j\omega)$','Interpreter','latex');
legend('Location','best','Interpreter','latex');

%% KS
figure('Name','Controller comparison - Control sensitivity');
hold on; grid on;
for k = 1:nControllers
    plotSigmaController( ...
        KS_scaled_all{k},omegaHinf,controllerNames{k});
end
plotSigmaBound(inv(WU),omegaHinf,'$W_U^{-1}$');
xlabel('$\omega\;[\mathrm{rad/s}]$','Interpreter','latex');
ylabel('Valori singolari [dB]','Interpreter','latex');
title('Sensibilita'' del controllo $K(j\omega)S(j\omega)$','Interpreter','latex');
legend('Location','best','Interpreter','latex');

%% T
figure('Name','Controller comparison - Complementary sensitivity');
hold on; grid on;
for k = 1:nControllers
    plotSigmaController( ...
        T_scaled_all{k},omegaHinf,controllerNames{k});
end
plotSigmaBound(inv(WT),omegaHinf,'$W_T^{-1}$');
xlabel('$\omega\;[\mathrm{rad/s}]$','Interpreter','latex');
ylabel('Valori singolari [dB]','Interpreter','latex');
title('Funzione di sensibilita'' complementare $T(j\omega)$','Interpreter','latex');
legend('Location','best','Interpreter','latex');

%% ========================================================================
% 8. MU PLOTS
% ========================================================================
for k = 1:nControllers
    figure( ...
        'Name', ...
        ['Mu - ',controllerNames{k}]);
    semilogx( ...
        omegaHinf, ...
        muNP_all{k}, ...
        'LineWidth',1.5);
    hold on;
    semilogx( ...
        omegaHinf, ...
        muRSupper_all{k}, ...
        'LineWidth',1.3);
    semilogx( ...
        omegaHinf, ...
        muRSlower_all{k}, ...
        '--');
    semilogx( ...
        omegaHinf, ...
        muRPupper_all{k}, ...
        'LineWidth',1.3);
    semilogx( ...
        omegaHinf, ...
        muRPlower_all{k}, ...
        '--');
    yline(1,'k:');
    grid on;
    xlabel('$\omega\;[\mathrm{rad/s}]$','Interpreter','latex');
    ylabel('$\mu$ / guadagno','Interpreter','latex');
    title( ...
        ['Analisi robusta $\mu$ - ',controllerNames{k}], ...
        'Interpreter','latex');
    legend( ...
        'NP', ...
        'mu RS upper', ...
        'mu RS lower', ...
        'mu RP upper', ...
        'mu RP lower', ...
        'limit', ...
        'Location','best');
end

%% ========================================================================
% 9. CONTROL EFFORT
% =========================================================================
% I due attuatori vengono mostrati in pannelli distinti. In precedenza
% quattro controllori x due attuatori producevano otto curve nello stesso
% axes e MATLAB riciclava la ColorOrder, assegnando lo stesso colore a
% tracce semanticamente diverse.
figure('Name','Controller comparison - Control effort for pitch reference');
tl = tiledlayout(2,1,'TileSpacing','compact','Padding','compact');

nexttile; hold on; grid on;
for k = 1:nControllers
    [u,t] = step( ...
        KS_phys_all{k}(:,1) * reference.alphaStep, ...
        tStep);
    plot( ...
        t,squeeze(u(:,1,1)), ...
        'LineWidth',1.3, ...
        'Color',controller_plot_color(controllerNames{k}), ...
        'DisplayName',controllerNames{k});
end
yline(scale.F1,'k:','HandleVisibility','off');
yline(-scale.F1,'k:','HandleVisibility','off');
ylabel('$\Delta F_{1,\mathrm{cmd}}\;[\mathrm{N}]$','Interpreter','latex');
title('Comando attuatore 1','Interpreter','latex');
legend('Location','best');

nexttile; hold on; grid on;
for k = 1:nControllers
    [u,t] = step( ...
        KS_phys_all{k}(:,1) * reference.alphaStep, ...
        tStep);
    plot( ...
        t,squeeze(u(:,2,1)), ...
        'LineWidth',1.3, ...
        'Color',controller_plot_color(controllerNames{k}), ...
        'DisplayName',controllerNames{k});
end
yline(scale.F2,'k:','HandleVisibility','off');
yline(-scale.F2,'k:','HandleVisibility','off');
xlabel('$t\;[\mathrm{s}]$','Interpreter','latex');
ylabel('$\Delta F_{2,\mathrm{cmd}}\;[\mathrm{N}]$','Interpreter','latex');
title('Comando attuatore 2','Interpreter','latex');
legend('Location','best');

sgtitle(tl,'Sforzo di controllo per riferimento di pitch','Interpreter','latex');

%% ========================================================================
% 10. TABELLA FINALE
% ========================================================================
results = table( ...
    controllerNames, ...
    controllerOrder, ...
    maxRealPoleNominal, ...
    performance_WS, ...
    freq_WS, ...
    performance_WU, ...
    freq_WU, ...
    performance_WT, ...
    freq_WT, ...
    gammaNominal, ...
    freqGamma, ...
    robustStabilityLower, ...
    robustStabilityUpper, ...
    worstCaseGainLower, ...
    worstCaseGainUpper, ...
    muRSpeakLower, ...
    muRSpeakUpper, ...
    muRPpeakLower, ...
    muRPpeakUpper, ...
    pitchRiseTime, ...
    pitchSettlingTime, ...
    pitchOvershoot, ...
    yawRiseTime, ...
    yawSettlingTime, ...
    yawOvershoot, ...
    NS_pass, ...
    NP_pass, ...
    RS_pass, ...
    RP_pass, ...
    PitchTimePass, ...
    PitchOvershootPass, ...
    YawTimePass, ...
    YawOvershootPass, ...
    'VariableNames',{
        'Controller'
        'Order'
        'MaxRealPole'
        'WS_S'
        'WS_PeakFrequency'
        'WU_KS'
        'WU_PeakFrequency'
        'WT_T'
        'WT_PeakFrequency'
        'NominalGamma'
        'GammaPeakFrequency'
        'RS_Lower'
        'RS_Upper'
        'WorstGainLower'
        'WorstGainUpper'
        'MuRS_Lower'
        'MuRS_Upper'
        'MuRP_Lower'
        'MuRP_Upper'
        'PitchRiseTime'
        'PitchSettlingTime'
        'PitchOvershoot'
        'YawRiseTime'
        'YawSettlingTime'
        'YawOvershoot'
        'NS'
        'NP'
        'RS'
        'RP'
        'PitchSettlingPass'
        'PitchOvershootPass'
        'YawSettlingPass'
        'YawOvershootPass'
    });
fprintf('\n============================================================\n');
fprintf('RISULTATI FINALI\n');
fprintf('============================================================\n');
disp(results);
writetable( ...
    results, ...
    'HINF_analysis_results.csv');
save( ...
    'HINF_analysis_results.mat', ...
    'results', ...
    'S_scaled_all', ...
    'T_scaled_all', ...
    'KS_scaled_all', ...
    'S_phys_all', ...
    'T_phys_all', ...
    'KS_phys_all', ...
    'GS_phys_all', ...
    'muNP_all', ...
    'muRSupper_all', ...
    'muRSlower_all', ...
    'muRPupper_all', ...
    'muRPlower_all');

%% ========================================================================
% FUNZIONE
% ========================================================================
function plotSigmaController(sys,omega,name)
%PLOTSIGMACONTROLLER Valori singolari con colore fisso per controllore.
    sv = sigma(sys,omega);
    sv = squeeze(sv);
    if isvector(sv)
        sv = reshape(sv,1,[]);
    elseif size(sv,2) ~= numel(omega) && size(sv,1) == numel(omega)
        sv = sv.';
    end

    c = controller_plot_color(name);
    styles = {'-','--',':','-.'};
    for isv = 1:size(sv,1)
        args = { ...
            'Color',c, ...
            'LineWidth',1.25, ...
            'LineStyle',styles{1+mod(isv-1,numel(styles))}};
        if isv == 1
            args = [args,{'DisplayName',name}]; %#ok<AGROW>
        else
            args = [args,{'HandleVisibility','off'}]; %#ok<AGROW>
        end
        semilogx(omega,20*log10(max(sv(isv,:),realmin)),args{:});
    end
end

function plotSigmaBound(sys,omega,labelText)
%PLOTSIGMABOUND Limite prestazionale in nero, senza duplicare la legenda.
    sv = sigma(sys,omega);
    sv = squeeze(sv);
    if isvector(sv)
        sv = reshape(sv,1,[]);
    elseif size(sv,2) ~= numel(omega) && size(sv,1) == numel(omega)
        sv = sv.';
    end

    styles = {'-.',':','--','-'};
    for isv = 1:size(sv,1)
        args = { ...
            'Color',[0.15 0.15 0.15], ...
            'LineWidth',1.1, ...
            'LineStyle',styles{1+mod(isv-1,numel(styles))}};
        if isv == 1
            args = [args,{'DisplayName',labelText}]; %#ok<AGROW>
        else
            args = [args,{'HandleVisibility','off'}]; %#ok<AGROW>
        end
        semilogx(omega,20*log10(max(sv(isv,:),realmin)),args{:});
    end
end

function text = passText(condition)
    if condition
        text = 'PASS';
    else
        text = 'FAIL';
    end
end
