%% HINF_SYNTHESIS
%
% Sintesi:
%
%   1) mixsyn
%   2) hinfsyn
%   3) hinfstruct:
%
%        PID alpha -> lead/lag alpha
%        PID beta  -> lead/lag beta

close all;
clc;

load('HINF_setup.mat');

I2 = eye(2);

nmeas = 2;
ncont = 2;

optsHinf = ...
    hinfsynOptions( ...
        'Display','on');

%% ========================================================================
% 1. MIXSYN
% ========================================================================

fprintf('\n============================================================\n');
fprintf('1. MIXSYN\n');
fprintf('============================================================\n');

[K_mix_scaled, ...
 CL_mix, ...
 gamma_mix, ...
 info_mix] = ...
    mixsyn( ...
        G_scaled, ...
        WS, ...
        WU, ...
        WT, ...
        optsHinf);

K_mix_scaled = ...
    minreal( ...
        ss(K_mix_scaled), ...
        1e-7);

K_mix = ...
    minreal( ...
        Du * ...
        K_mix_scaled * ...
        Dy_inv, ...
        1e-7);

fprintf( ...
    'Gamma mixsyn = %.8f\n', ...
    gamma_mix);

fprintf( ...
    'Ordine K_mix = %d\n', ...
    order(K_mix_scaled));

%% ========================================================================
% 2. HINFSYN
% ========================================================================

fprintf('\n============================================================\n');
fprintf('2. HINFSYN\n');
fprintf('============================================================\n');

[K_hinfsyn_scaled, ...
 CL_hinfsyn, ...
 gamma_hinfsyn, ...
 info_hinfsyn] = ...
    hinfsyn( ...
        P_mix, ...
        nmeas, ...
        ncont, ...
        optsHinf);

K_hinfsyn_scaled = ...
    minreal( ...
        ss(K_hinfsyn_scaled), ...
        1e-7);

K_hinfsyn = ...
    minreal( ...
        Du * ...
        K_hinfsyn_scaled * ...
        Dy_inv, ...
        1e-7);

fprintf( ...
    'Gamma hinfsyn = %.8f\n', ...
    gamma_hinfsyn);

fprintf( ...
    'Ordine K_hinfsyn = %d\n', ...
    order(K_hinfsyn_scaled));

fprintf( ...
    'Differenza relativa gamma = %.6e\n', ...
    abs(gamma_mix-gamma_hinfsyn) / ...
    gamma_mix);

%% ========================================================================
% 3. HINFSTRUCT:
%
% PID + COMPENSATORE DINAMICO
% ========================================================================

fprintf('\n============================================================\n');
fprintf('3. HINFSTRUCT - PID + LEAD/LAG\n');
fprintf('============================================================\n');

%% ========================================================================
% 3.1 PID INIZIALI FISICI
% ========================================================================

Kp_alpha_phys_0 = -0.2147;
Ki_alpha_phys_0 =  1.4066;

Kp_beta_phys_0 =  ...
     0.2149;

Ki_beta_phys_0 = ...
     0.0444;

%% Conversione in coordinate normalizzate

alphaPhysToScaled = ...
    scale.alpha / scale.F1;

betaPhysToScaled = ...
    scale.beta / scale.F2;

%% PID alpha

Kalpha_tunable = ...
    tunablePID( ...
        'Kalpha', ...
        'PID');

Kalpha_tunable.Kp.Value = ...
    alphaPhysToScaled * ...
    Kp_alpha_phys_0;

Kalpha_tunable.Ki.Value = ...
    alphaPhysToScaled * ...
    Ki_alpha_phys_0;

Kalpha_tunable.Kd.Value = ...
    0;

Kalpha_tunable.Tf.Value = ...
    0.02;

%% PID beta

Kbeta_tunable = ...
    tunablePID( ...
        'Kbeta', ...
        'PID');

Kbeta_tunable.Kp.Value = ...
    betaPhysToScaled * ...
    Kp_beta_phys_0;

Kbeta_tunable.Ki.Value = ...
    betaPhysToScaled * ...
    Ki_beta_phys_0;

Kbeta_tunable.Kd.Value = ...
    0;

Kbeta_tunable.Tf.Value = ...
    0.02;

%% Vincoli

Kalpha_tunable.Ki.Minimum = ...
    1e-10;

Kbeta_tunable.Ki.Minimum = ...
    1e-10;

Kalpha_tunable.Tf.Minimum = ...
    1e-4;

Kbeta_tunable.Tf.Minimum = ...
    1e-4;

%% ========================================================================
% 3.2 COMPENSATORI DINAMICI
%
% Inizializzazione più coerente con la nuova banda.
%
% Pitch:
%
%     1 + s/2.5
% ----------------
%      1 + s/8
%
%
% Yaw:
%
%      1 + s/2
% ----------------
%      1 + s/6
% ========================================================================

Falpha0 = ...
    (1 + s/2.5) / ...
    (1 + s/8);

Fbeta0 = ...
    (1 + s/2.0) / ...
    (1 + s/6);

Falpha_tunable = ...
    tunableTF( ...
        'Falpha', ...
        tf(Falpha0));

Fbeta_tunable = ...
    tunableTF( ...
        'Fbeta', ...
        tf(Fbeta0));

%% ========================================================================
% 3.3 CONTROLLORE STRUTTURATO
% ========================================================================

Calpha_tunable = ...
    Falpha_tunable * ...
    Kalpha_tunable;

Cbeta_tunable = ...
    Fbeta_tunable * ...
    Kbeta_tunable;

K_pidcomp_tunable = ...
    blkdiag( ...
        Calpha_tunable, ...
        Cbeta_tunable);

%% ========================================================================
% 3.4 CLOSED LOOP TUNABLE
% ========================================================================

L_pidcomp_tunable = ...
    G_scaled * ...
    K_pidcomp_tunable;

S_pidcomp_tunable = ...
    feedback( ...
        I2, ...
        L_pidcomp_tunable);

T_pidcomp_tunable = ...
    feedback( ...
        L_pidcomp_tunable, ...
        I2);

KS_pidcomp_tunable = ...
    K_pidcomp_tunable * ...
    S_pidcomp_tunable;

%% ========================================================================
% 3.5 OBIETTIVO H-INFINITY
% ========================================================================

CL_pidcomp_tunable = [
    WS*S_pidcomp_tunable
    WU*KS_pidcomp_tunable
    WT*T_pidcomp_tunable
];

%% ========================================================================
% 3.6 HINFSTRUCT
% ========================================================================

rng(10);

optsHinfStruct = ...
    hinfstructOptions( ...
        'Display','final', ...
        'RandomStart',30, ...
        'StableOffset',1e-2, ...
        'TargetGain',0);

[CL_pidcomp_tuned, ...
 gamma_pidcomp, ...
 info_pidcomp] = ...
    hinfstruct( ...
        CL_pidcomp_tunable, ...
        optsHinfStruct);

%% ========================================================================
% 3.7 ESTRAZIONE PARAMETRI
% ========================================================================

Kalpha_tuned_scaled = ...
    getBlockValue( ...
        CL_pidcomp_tuned, ...
        'Kalpha');

Kbeta_tuned_scaled = ...
    getBlockValue( ...
        CL_pidcomp_tuned, ...
        'Kbeta');

Falpha_tuned = ...
    getBlockValue( ...
        CL_pidcomp_tuned, ...
        'Falpha');

Fbeta_tuned = ...
    getBlockValue( ...
        CL_pidcomp_tuned, ...
        'Fbeta');

%% ========================================================================
% 3.8 CONTROLLORE NUMERICO
% ========================================================================

Calpha_scaled = ...
    minreal( ...
        ss(Falpha_tuned) * ...
        ss(Kalpha_tuned_scaled), ...
        1e-7);

Cbeta_scaled = ...
    minreal( ...
        ss(Fbeta_tuned) * ...
        ss(Kbeta_tuned_scaled), ...
        1e-7);

K_pidcomp_scaled = ...
    blkdiag( ...
        Calpha_scaled, ...
        Cbeta_scaled);

K_pidcomp_scaled = ...
    minreal( ...
        ss(K_pidcomp_scaled), ...
        1e-7);

%% ========================================================================
% 3.9 CONVERSIONE FISICA
% ========================================================================

K_pidcomp = ...
    minreal( ...
        Du * ...
        K_pidcomp_scaled * ...
        Dy_inv, ...
        1e-7);

%% PID fisici

alphaScaledToPhys = ...
    scale.F1 / scale.alpha;

betaScaledToPhys = ...
    scale.F2 / scale.beta;

Kalpha_tuned = ...
    pid( ...
        alphaScaledToPhys * ...
        Kalpha_tuned_scaled.Kp, ...
        alphaScaledToPhys * ...
        Kalpha_tuned_scaled.Ki, ...
        alphaScaledToPhys * ...
        Kalpha_tuned_scaled.Kd, ...
        Kalpha_tuned_scaled.Tf);

Kbeta_tuned = ...
    pid( ...
        betaScaledToPhys * ...
        Kbeta_tuned_scaled.Kp, ...
        betaScaledToPhys * ...
        Kbeta_tuned_scaled.Ki, ...
        betaScaledToPhys * ...
        Kbeta_tuned_scaled.Kd, ...
        Kbeta_tuned_scaled.Tf);

%% Compensatori per Simulink

[numFalpha,denFalpha] = ...
    tfdata( ...
        tf(Falpha_tuned), ...
        'v');

[numFbeta,denFbeta] = ...
    tfdata( ...
        tf(Fbeta_tuned), ...
        'v');

%% ========================================================================
% 3.10 VERIFICA
% ========================================================================

L_pidcomp = ...
    G_scaled * ...
    K_pidcomp_scaled;

S_pidcomp = ...
    feedback( ...
        I2, ...
        L_pidcomp);

T_pidcomp = ...
    feedback( ...
        L_pidcomp, ...
        I2);

KS_pidcomp = ...
    K_pidcomp_scaled * ...
    S_pidcomp;

[gWS_pidcomp,wWS_pidcomp] = ...
    hinfnorm( ...
        minreal( ...
            WS*S_pidcomp, ...
            1e-7));

[gWU_pidcomp,wWU_pidcomp] = ...
    hinfnorm( ...
        minreal( ...
            WU*KS_pidcomp, ...
            1e-7));

[gWT_pidcomp,wWT_pidcomp] = ...
    hinfnorm( ...
        minreal( ...
            WT*T_pidcomp, ...
            1e-7));

CLcheck = [
    WS*S_pidcomp
    WU*KS_pidcomp
    WT*T_pidcomp
];

[gALL_pidcomp,wALL_pidcomp] = ...
    hinfnorm( ...
        minreal( ...
            CLcheck, ...
            1e-7));

fprintf('\n============================================================\n');
fprintf('HINFSTRUCT RESULT\n');
fprintf('============================================================\n');

fprintf( ...
    'Gamma synthesis = %.6f\n', ...
    gamma_pidcomp);

fprintf( ...
    'Gamma verified  = %.6f\n', ...
    gALL_pidcomp);

fprintf( ...
    'WS*S  = %.6f\n', ...
    gWS_pidcomp);

fprintf( ...
    'WU*KS = %.6f\n', ...
    gWU_pidcomp);

fprintf( ...
    'WT*T  = %.6f\n', ...
    gWT_pidcomp);

fprintf( ...
    'Max Re(polo) = %.6e\n', ...
    max(real(pole(T_pidcomp))));

disp('PID alpha:');
disp(Kalpha_tuned);

disp('Falpha:');
disp(tf(Falpha_tuned));

disp('PID beta:');
disp(Kbeta_tuned);

disp('Fbeta:');
disp(tf(Fbeta_tuned));

%% ========================================================================
% 4. CONTROLLORI
% ========================================================================

controllersScaled = {
    K_mix_scaled
    K_hinfsyn_scaled
    K_pidcomp_scaled
};

controllersPhysical = {
    K_mix
    K_hinfsyn
    K_pidcomp
};

controllerNames = {
    'mixsyn'
    'hinfsyn'
    'PID + compensator'
};

%% ========================================================================
% 5. SALVATAGGIO
% ========================================================================

nControllers = ncont;


save('HINF_controllers.mat', ...
    'K_mix_scaled', ...
    'K_hinfsyn_scaled', ...
    'K_pidcomp_scaled', ...
    'K_mix', ...
    'K_hinfsyn', ...
    'K_pidcomp', ...
    'Kalpha_tuned_scaled', ...
    'Kbeta_tuned_scaled', ...
    'Kalpha_tuned', ...
    'Kbeta_tuned', ...
    'Falpha_tuned', ...
    'Fbeta_tuned', ...
    'numFalpha', ...
    'denFalpha', ...
    'numFbeta', ...
    'denFbeta', ...
    'gamma_mix', ...
    'gamma_hinfsyn', ...
    'gamma_pidcomp', ...
    'info_mix', ...
    'info_hinfsyn', ...
    'info_pidcomp', ...
    'nControllers');

fprintf('\nHINF_controllers.mat creato correttamente.\n');